### ISSUE TITLE
v2.0 Migration Checklist

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3503]
# v2.0 Migration Checklist

## High Priority
These items must be completed before moving to other v2.0 work.

### Props Naming and Values
- [ ] Replace `left`/`right` with `start`/`end` in props names and values
  - [ ] Add `@deprecated` tags in v1
- [ ] Standardize props naming convention
  - [ ] Remove `is` prefix (e.g., `isOpen` → `open`, `isDisabled` → `disabled`)
  - [ ] Standardize `orientation`/`direction` usage
  - [ ] Add `@deprecated` tags in v1

#### @yamada-ui/layouts
- [ ] Rename `Divider` to `Separator`
  - [ ] Add `@deprecated` tag in v1

#### @yamada-ui/button
- [ ] Make `aria-label` required in `IconButton`

#### @yamada-ui/icon
- [ ] Remove `size` prop
- [ ] Remove all `InfoIcon` and similar icons
  - [ ] Add `@deprecated` tags in v1

#### @yamada-ui/loading
- [ ] Remove `size` prop

#### @yamada-ui/image
- [ ] Remove `size` prop

#### @yamada-ui/input
- [ ] Remove `isClick` from `InputElement`

#### @yamada-ui/progress
- [x] Remove `size` prop from `CircleProgress`

#### @yamada-ui/fontawesome
- [x] Rename `Icon` to `FontawesomeIcon`

#### @yamada-ui/lucide
- [ ] Rename `Icon` to `LucideIcon`
- [ ] Add `Icon` suffix to all component names
- [ ] Add `@deprecated` tags to components without `Icon` suffix in v1

### Styling and Components
- [ ] Migrate styling to theme
- [ ] Replace component icons with `@yamada-ui/lucide` icons

### Package Updates
- [ ] Migrate `@yamada-ui/use-popper` and `@yamada-ui/popover` to [floating-ui](https://floating-ui.com/docs/migration)

### Code Architecture
- [ ] Move state and props logic to hooks
- [ ] Review and update `className` to comply with [BEM](https://getbem.com/) conventions

#### @yamada-ui/table
- [ ] Rebuild to remove hidden TanStack Table dependency and add extensions

#### @yamada-ui/notice
- [ ] Replace with [Sonner](https://sonner.emilkowal.ski/)

#### @yamada-ui/charts
- [ ] Add support for combining multiple charts

### Theme
- [ ] Enhance `animations` tokens
