### ISSUE TITLE
Make components headless for `Menu` component

### ISSUE THREAD

**Issue by chida09** [yamada-ui/yamada-ui#3910]
### Description
Migrate styles from components to themes.
Since component styles in themes inherit styles from other components using mergeStyle etc., duplicate styles should be removed.

### TODO
- [x] packages/react/src/components/menu/context-menu-trigger.tsx
- [x] packages/react/src/components/menu/menu-button.tsx
- [x] packages/react/src/components/menu/menu-context.ts
- [x] packages/react/src/components/menu/menu-divider.tsx
- [x] packages/react/src/components/menu/menu-group.tsx
- [x] packages/react/src/components/menu/menu-item.tsx
- [x] packages/react/src/components/menu/menu-separator.tsx

### Problem Statement/Justification
Move static styles from menu component to theme.

### Proposed Solution or API
*No response*

### Alternatives
*No response*

### Are you willing to participate in implementing this feature and create a pull request include the implementation?
Yes

### Additional Information
*No response*
