### ISSUE TITLE
Make components headless for `Select` component

### ISSUE THREAD

**Issue by chida09** [yamada-ui/yamada-ui#3930]
### Description
Migrate styles from components to themes.
Since component styles in themes inherit styles from other components using mergeStyle etc., duplicate styles should be removed.

### Problem Statement/Justification
Move static styles from select component to theme.

### TODO
- [ ] packages/react/src/components/select/multi-select.tsx
- [ ] packages/react/src/components/select/option.tsx
- [ ] packages/react/src/components/select/select-icon.tsx
- [ ] packages/react/src/components/select/select.tsx

### Proposed Solution or API
*No response*

### Alternatives
*No response*

### Are you willing to participate in implementing this feature and create a pull request include the implementation?
Yes

### Additional Information
*No response*
